spring.application.name=enterprise-apps

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=JOUW_MAILTRAP_USERNAME_HIER
spring.mail.password=JOUW_MAILTRAP_PASSWORD_HIER